{application,node,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{node_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[git_lib,node,node_app,node_lib,node_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
